
name: Action workflow

on: [push]

jobs: 
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: simple javascript actions
        id: hello 
        uses: actions/hello-world-javascript-action@v2
        with:
          who-to-greet: chetan

      - name: Get the output time
        run: echo "${{ steps.hello.output.time }}"

