name: Action workflow

on: push
  #pull_request:
  #  types: [closed, assigned ,opened, reopened]


jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -alrt
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
      - name: Checkout 
        uses: actions/checkout@v1

      - name: List file after checkout 
        run : |
          pwd
          ls -alrt

      - name: Simple Javascript Action 
        id: hello 
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: chetan
