name: Pass value ENV var
on: [push]
  branches: "main 
jobs:
  job1:
    runs-on: ubuntu-latest
   
    steps:
      - name: Set environment variable
        run: echo "MY_VAR=Hello from job1" >> $GITHUB_ENV

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Access environment variable
        run: echo "Received variable: $MY_VAR"

