name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
          run: echo "My first workflow"
      - name: multiline script
          run:
            node -v
            npm -v
            
    
