name: shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: string
<<<<<<< HEAD
        run: echo "hey my first action"
      - name: multiline script
        run: |
             node -v
             npm -v
=======
          run: echo "My first workflow"
      - name: multiline script
          run: |
            node -v
            npm -v
>>>>>>> 5534eb796cf53807b3708913f93fcb5f62e641cb
            
    
